//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainApplication.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [JsonIgnore]
        public static string TYPE_LIBRE = "libre";
        [JsonIgnore]
        public static string TYPE_GERE = "gere";

        public Client()
        {
            this.valeurs_client = new HashSet<ValeursClient>();
            this.ordre_A = new HashSet<OrdreAchat>();
            this.ordre_V = new HashSet<OrdreVente>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<double> solde { get; set; }
        public string type { get; set; }
    
        [JsonIgnore]
        public virtual ICollection<ValeursClient> valeurs_client { get; set; }
        [JsonIgnore]
        public virtual ICollection<OrdreAchat> ordre_A { get; set; }
        [JsonIgnore]
        public virtual ICollection<OrdreVente> ordre_V { get; set; }
    }
}
