//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valeur
    {
        public string SEANCE { get; set; }
        public string GROUPE { get; set; }
        public string CODE { get; set; }
        public string VALEUR { get; set; }
        public string COURS_REF { get; set; }
        public string COURS_VEILLE { get; set; }
        public string OUV { get; set; }
        public string PLUS_BAS { get; set; }
        public string PLUS_HAUT { get; set; }
        public string CLOTURE { get; set; }
        public string P_MOY_POND { get; set; }
        public string I_RES { get; set; }
        public string SEUIL_BAS { get; set; }
        public string SEUIL_HAUT { get; set; }
        public string QTTE_TOT { get; set; }
        public string VOLUME_TOT { get; set; }
        public string QTE_SANS_BLOC { get; set; }
        public string TOT_SANS_BLOC { get; set; }
    }
}
