//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarcheFinancier.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IibServices")]
    public interface IibServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IibServices/GetData", ReplyAction="http://tempuri.org/IibServices/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IibServices/GetData", ReplyAction="http://tempuri.org/IibServices/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IibServices/GetCotationsJsonList", ReplyAction="http://tempuri.org/IibServices/GetCotationsJsonListResponse")]
        string GetCotationsJsonList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IibServices/GetCotationsJsonList", ReplyAction="http://tempuri.org/IibServices/GetCotationsJsonListResponse")]
        System.Threading.Tasks.Task<string> GetCotationsJsonListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IibServices/GetClientValeurs", ReplyAction="http://tempuri.org/IibServices/GetClientValeursResponse")]
        string GetClientValeurs(string login, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IibServices/GetClientValeurs", ReplyAction="http://tempuri.org/IibServices/GetClientValeursResponse")]
        System.Threading.Tasks.Task<string> GetClientValeursAsync(string login, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IibServices/GetSolde", ReplyAction="http://tempuri.org/IibServices/GetSoldeResponse")]
        string GetSolde(string login, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IibServices/GetSolde", ReplyAction="http://tempuri.org/IibServices/GetSoldeResponse")]
        System.Threading.Tasks.Task<string> GetSoldeAsync(string login, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IibServicesChannel : MarcheFinancier.ServiceReference1.IibServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IibServicesClient : System.ServiceModel.ClientBase<MarcheFinancier.ServiceReference1.IibServices>, MarcheFinancier.ServiceReference1.IibServices {
        
        public IibServicesClient() {
        }
        
        public IibServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IibServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IibServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IibServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string GetCotationsJsonList() {
            return base.Channel.GetCotationsJsonList();
        }
        
        public System.Threading.Tasks.Task<string> GetCotationsJsonListAsync() {
            return base.Channel.GetCotationsJsonListAsync();
        }
        
        public string GetClientValeurs(string login, string Password) {
            return base.Channel.GetClientValeurs(login, Password);
        }
        
        public System.Threading.Tasks.Task<string> GetClientValeursAsync(string login, string Password) {
            return base.Channel.GetClientValeursAsync(login, Password);
        }
        
        public string GetSolde(string login, string Password) {
            return base.Channel.GetSolde(login, Password);
        }
        
        public System.Threading.Tasks.Task<string> GetSoldeAsync(string login, string Password) {
            return base.Channel.GetSoldeAsync(login, Password);
        }
    }
}
